name: Basic health check (Install dependencies and run the script)

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'

  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Running the file in test mode
      run: |
        cd elevenclock
        python -m compileall -q .
        
