name: Retrieve latest translations from Tolgee

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  main:
    runs-on: windows-latest
    env:
        TOLGEE_KEY: "${{ secrets.TOLGEE_TOKEN }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Download Tolgee translations
        run: |
          python scripts/download_translations.py --autocommit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          base: main
          token: "${{ secrets.REPO_SCOPED_TOKEN }}"
          labels: tolgee-ci
          title: "Load translations from Tolgee"
          body: ""
          assignees: marticliment
          author: "Martí Climent <marticlilop@gmail.com>"
          commit-message:  |
            Load updated translations from Tolgee
            Co-authored-by: Martí Climent from the multiverse <121457539+martinet101@users.noreply.github.com>
          branch: pull-request/update-translation
